# -*- coding: utf-8 -*-
"""newpractical3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QS_ullWR8I5nh8_xAnSMbIJaMNu6MCd3
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
#load dataset

iris=load_iris()
X=iris.data
y=iris.target
df=pd.DataFrame(X,columns=iris.feature_names)
df["species"]=iris.target
print(df.head())
print("Features Name : ",iris.feature_names)
print("Target data : ",iris.target)
print("Target Names: ",iris.target_names)
#print("X---------------------->",X)
#split data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3, random_state=42)
#create model
model =LogisticRegression(max_iter=200)
#train model
model.fit(X_train,y_train)
#make prediction
y_pred=model.predict(X_test)
#confusion matrix
cm=confusion_matrix(y_test,y_pred)

#evolution
print("accuracy:",accuracy_score(y_test,y_pred))
print("confusion matrix:\n",confusion_matrix(y_test,y_pred))
print("classification report:\n",classification_report(y_test,y_pred))