# -*- coding: utf-8 -*-
"""practicalnext.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SH03bzcAZ68sXhm42DciWLKHNqwH1y_o
"""

#import libraries
import pandas as pd
import numpy as np
from sklearn.datasets import load_diabetes
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error, r2_score
from sklearn.model_selection import cross_val_score
#load dataset
diabetes=load_diabetes()
X=diabetes.data
y=diabetes.target
#create dataframe
df=pd.DataFrame(diabetes.data,columns=diabetes.feature_names)
print(df.head())
#split data
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)
#create model
model=LinearRegression()
#train model
model.fit(X_train,y_train)
#prediction
y_pred=model.predict(X_test)
#evolution
mae=mean_absolute_error(y_test,y_pred)
mse=mean_squared_error(y_test,y_pred)
rmse=np.sqrt(mse)
r2=r2_score(y_test,y_pred)
# #fit model
# model.fit(X_train,y_train)
print("mae",mae)
print("mse",mse)
print("rmse",rmse)
print("r2 score",r2)
scores=cross_val_score(model,X_train,y_train,cv=5)
print("cross val score",scores)
print("mean cross val score",scores.mean())