# -*- coding: utf-8 -*-
"""practical7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-kic4YM3QkTjKgY-NDxcQZgfelTF7IBK
"""

import pandas as pd
from sklearn.preprocessing import StandardScaler
df=pd.DataFrame({"Age":[20,25,30],"Salary":[20000,50000,80000]})
print(df)
scaler=StandardScaler()
df_scaled=scaler.fit_transform(df)
print(df_scaled)
scaled_data=pd.DataFrame(df_scaled,columns=df.columns)
print(scaled_data )

from sklearn.preprocessing import MinMaxScaler
df=pd.DataFrame({"Income":[15000,18000,20000,22000,25000,30000,100000]})
#initialize scaler
scaler=MinMaxScaler()
#apply scaling
df["Scaled_Income"]=scaler.fit_transform(df[["Income"]])
print(df)

import numpy as np
import pandas as pd
from sklearn.preprocessing import LabelEncoder
performance=["poor","Good","Excellent ","Average"]
print(type(performance))
le=LabelEncoder()
le.fit(performance)#learn parameter
le.transform(performance)#applies transformation
le.fit_transform(performance)#both learn and transform

import pandas as pd
from sklearn.feature_selection import SelectKBest,f_classif
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import MinMaxScaler
df=pd.DataFrame({"Name":["A","B","C","D","E"],"Gender":["Male","Female","Female","Male","Male"],"Math":[85,78,92,70,60],"Science":[90,80,85,75,65],"English":[70,65,80,60,55],"Pass":[1,1,1,0,0]})
#1. Encode Gender
le=LabelEncoder()
df["Gender_encoded"]=le.fit_transform(df['Gender'])
print(df)

#2. feature scaling(math,science,english)

scaler=MinMaxScaler()
df[["Math_scaled","Science_scaled","English_scaled"]]=scaler.fit_transform(df[["Math","Science","English"]])
print(df)

#3. feature selection (select top 2 features)

#feature to consider (scaled + encoded)
X=df[["Gender_encoded","Math_scaled","Science_scaled","English_scaled"]]
Y=df["Pass"]

#selecting top 2 features

selector=SelectKBest(score_func=f_classif,k=2)
X_new=selector.fit_transform(X,Y)

selected_features=X.columns[selector.get_support()]
print(selected_features)
print("selected features:",list(selected_features))
print("Transformed Data:\n",X_new)

new_dataframe=pd.DataFrame(X_new,columns=selected_features)
print(new_dataframe)

#df_combined =pd.concat([df_old,df_new],axis=1)
df_combined=pd.concat([df,new_dataframe],axis=1)#vertically data add (column-wise)
print(df_combined)